// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActivityByResource = `-- name: CountActivityByResource :one
SELECT count(*) FROM activity_logs
WHERE organization_id = $1
  AND resource_type = $2
  AND resource_id = $3
`

type CountActivityByResourceParams struct {
	OrganizationID uuid.UUID
	ResourceType   string
	ResourceID     uuid.UUID
}

func (q *Queries) CountActivityByResource(ctx context.Context, arg CountActivityByResourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityByResource, arg.OrganizationID, arg.ResourceType, arg.ResourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_logs (organization_id, actor_user_id, action, resource_type, resource_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateActivityLogParams struct {
	OrganizationID uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	ResourceType   string
	ResourceID     uuid.UUID
	Metadata       []byte
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.Exec(ctx, createActivityLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}

const listActivityByResource = `-- name: ListActivityByResource :many
SELECT id, organization_id, actor_user_id, action, resource_type, resource_id, metadata, created_at FROM activity_logs
WHERE organization_id = $1
  AND resource_type = $2
  AND resource_id = $3
ORDER BY created_at DESC, id DESC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListActivityByResourceParams struct {
	OrganizationID uuid.UUID
	ResourceType   string
	ResourceID     uuid.UUID
	PageOffset     int64
	PageLimit      int64
}

func (q *Queries) ListActivityByResource(ctx context.Context, arg ListActivityByResourceParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityByResource,
		arg.OrganizationID,
		arg.ResourceType,
		arg.ResourceID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
