// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT count(*) FROM api_keys
WHERE organization_id = $1
  AND ($2::bool OR revoked_at IS NULL)
`

type CountAPIKeysParams struct {
	OrganizationID uuid.UUID
	IncludeRevoked bool
}

func (q *Queries) CountAPIKeys(ctx context.Context, arg CountAPIKeysParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeys, arg.OrganizationID, arg.IncludeRevoked)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    organization_id, created_by, name, key_prefix, key_last_four, key_hash, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, created_by, name, key_prefix, key_last_four, key_hash, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type CreateAPIKeyParams struct {
	OrganizationID uuid.UUID
	CreatedBy      uuid.UUID
	Name           string
	KeyPrefix      string
	KeyLastFour    string
	KeyHash        string
	ExpiresAt      time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyLastFour,
		arg.KeyHash,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyLastFour,
		&i.KeyHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, organization_id, created_by, name, key_prefix, key_last_four, key_hash, expires_at, revoked_at, last_used_at, created_at, updated_at FROM api_keys
WHERE key_hash = $1
`

// Authentication resolves a key by hash before a tenant is known, so this lookup
// runs without an RLS tenant context, exactly like the login lookup by email.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyLastFour,
		&i.KeyHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, organization_id, created_by, name, key_prefix, key_last_four, key_hash, expires_at, revoked_at, last_used_at, created_at, updated_at FROM api_keys
WHERE id = $1 AND organization_id = $2
`

type GetAPIKeyByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, arg.ID, arg.OrganizationID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyLastFour,
		&i.KeyHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByIDForUpdate = `-- name: GetAPIKeyByIDForUpdate :one
SELECT id, organization_id, created_by, name, key_prefix, key_last_four, key_hash, expires_at, revoked_at, last_used_at, created_at, updated_at FROM api_keys
WHERE id = $1 AND organization_id = $2
FOR UPDATE
`

type GetAPIKeyByIDForUpdateParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetAPIKeyByIDForUpdate(ctx context.Context, arg GetAPIKeyByIDForUpdateParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByIDForUpdate, arg.ID, arg.OrganizationID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyLastFour,
		&i.KeyHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, organization_id, created_by, name, key_prefix, key_last_four, key_hash, expires_at, revoked_at, last_used_at, created_at, updated_at FROM api_keys
WHERE organization_id = $1
  AND ($2::bool OR revoked_at IS NULL)
ORDER BY
    CASE WHEN $3::text = 'created_at' AND NOT $4::bool THEN created_at END ASC,
    CASE WHEN $3::text = 'created_at' AND $4::bool THEN created_at END DESC,
    CASE WHEN $3::text = 'expires_at' AND NOT $4::bool THEN expires_at END ASC,
    CASE WHEN $3::text = 'expires_at' AND $4::bool THEN expires_at END DESC,
    CASE WHEN $3::text = 'last_used_at' AND NOT $4::bool THEN last_used_at END ASC NULLS LAST,
    CASE WHEN $3::text = 'last_used_at' AND $4::bool THEN last_used_at END DESC NULLS LAST,
    name ASC,
    id ASC
LIMIT $6::bigint OFFSET $5::bigint
`

type ListAPIKeysParams struct {
	OrganizationID uuid.UUID
	IncludeRevoked bool
	SortBy         string
	SortDesc       bool
	PageOffset     int64
	PageLimit      int64
}

// Sort keys are fixed CASE branches, so client input never becomes SQL.
func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys,
		arg.OrganizationID,
		arg.IncludeRevoked,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyLastFour,
			&i.KeyHash,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredAPIKeys = `-- name: ListExpiredAPIKeys :many
SELECT id, organization_id, created_by, name, key_prefix, key_last_four, key_hash, expires_at, revoked_at, last_used_at, created_at, updated_at FROM api_keys
WHERE organization_id = $1
  AND revoked_at IS NULL
  AND expires_at < $2
ORDER BY expires_at ASC
LIMIT $3::bigint
`

type ListExpiredAPIKeysParams struct {
	OrganizationID uuid.UUID
	ExpiredBefore  time.Time
	RowLimit       int64
}

// Expired keys that have been dead long enough to be worth revoking. The grace
// period keeps recently expired keys visible for an operator to review.
func (q *Queries) ListExpiredAPIKeys(ctx context.Context, arg ListExpiredAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listExpiredAPIKeys, arg.OrganizationID, arg.ExpiredBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyLastFour,
			&i.KeyHash,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = $1
WHERE id = $2 AND organization_id = $3
  AND revoked_at IS NULL
RETURNING id, organization_id, created_by, name, key_prefix, key_last_four, key_hash, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type RevokeAPIKeyParams struct {
	RevokedAt      *time.Time
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.RevokedAt, arg.ID, arg.OrganizationID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyLastFour,
		&i.KeyHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAPIKeyByID = `-- name: RevokeAPIKeyByID :exec
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND organization_id = $2
`

type RevokeAPIKeyByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) RevokeAPIKeyByID(ctx context.Context, arg RevokeAPIKeyByIDParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyByID, arg.ID, arg.OrganizationID)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// Throttled to one write per minute per key so recording usage does not double
// the write load of every authenticated request.
func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
