// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE organization_id = $1
  AND ($2::text IS NULL OR action = $2::text)
  AND ($3::text IS NULL OR outcome = $3::text)
  AND ($4::uuid IS NULL OR actor_user_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR created_at >= $5::timestamptz)
`

type CountAuditLogsParams struct {
	OrganizationID *uuid.UUID
	Action         *string
	Outcome        *string
	ActorUserID    *uuid.UUID
	Since          *time.Time
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.OrganizationID,
		arg.Action,
		arg.Outcome,
		arg.ActorUserID,
		arg.Since,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    organization_id, actor_user_id, action, outcome, target_type, target_id,
    ip_address, user_agent, request_id, trace_id, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, organization_id, actor_user_id, action, outcome, target_type, target_id, ip_address, user_agent, request_id, trace_id, metadata, created_at
`

type CreateAuditLogParams struct {
	OrganizationID *uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	Outcome        string
	TargetType     *string
	TargetID       *string
	IpAddress      *string
	UserAgent      *string
	RequestID      *string
	TraceID        *string
	Metadata       []byte
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.Outcome,
		arg.TargetType,
		arg.TargetID,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.TraceID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ActorUserID,
		&i.Action,
		&i.Outcome,
		&i.TargetType,
		&i.TargetID,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.TraceID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
    id, organization_id, actor_user_id, action, outcome, target_type, target_id,
    CAST(COALESCE(host(ip_address), '') AS text) AS ip_address, user_agent, request_id, trace_id, metadata, created_at
FROM audit_logs
WHERE organization_id = $1
  AND ($2::text IS NULL OR action = $2::text)
  AND ($3::text IS NULL OR outcome = $3::text)
  AND ($4::uuid IS NULL OR actor_user_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR created_at >= $5::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $7::bigint OFFSET $6::bigint
`

type ListAuditLogsParams struct {
	OrganizationID *uuid.UUID
	Action         *string
	Outcome        *string
	ActorUserID    *uuid.UUID
	Since          *time.Time
	PageOffset     int64
	PageLimit      int64
}

type ListAuditLogsRow struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	Outcome        string
	TargetType     *string
	TargetID       *string
	IpAddress      string
	UserAgent      *string
	RequestID      *string
	TraceID        *string
	Metadata       []byte
	CreatedAt      time.Time
}

// Reads are always tenant-scoped; rows without an organization are excluded by the
// RLS select policy and can never be reached through this query.
// ip_address is selected as text: pgx cannot scan the inet type into a Go string,
// and the text form is what the API exposes anyway. An absent address becomes an
// empty string, which the client-facing entry omits.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.OrganizationID,
		arg.Action,
		arg.Outcome,
		arg.ActorUserID,
		arg.Since,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.Action,
			&i.Outcome,
			&i.TargetType,
			&i.TargetID,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.TraceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
