// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations
SET status = 'accepted',
    accepted_at = $1,
    accepted_by = $2
WHERE id = $3 AND organization_id = $4
RETURNING id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at
`

type AcceptInvitationParams struct {
	AcceptedAt     *time.Time
	AcceptedBy     *uuid.UUID
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation,
		arg.AcceptedAt,
		arg.AcceptedBy,
		arg.ID,
		arg.OrganizationID,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countInvitations = `-- name: CountInvitations :one
SELECT count(*) FROM invitations
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::citext IS NULL OR email = $3::citext)
`

type CountInvitationsParams struct {
	OrganizationID uuid.UUID
	Status         *string
	Email          *string
}

func (q *Queries) CountInvitations(ctx context.Context, arg CountInvitationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitations, arg.OrganizationID, arg.Status, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    organization_id, email, role_id, status, token_hash, invited_by, expires_at
)
VALUES ($1, $2, $3, 'pending', $4, $5, $6)
RETURNING id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at
`

type CreateInvitationParams struct {
	OrganizationID uuid.UUID
	Email          string
	RoleID         uuid.UUID
	TokenHash      string
	InvitedBy      uuid.UUID
	ExpiresAt      time.Time
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.RoleID,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveMembershipByEmail = `-- name: GetActiveMembershipByEmail :one
SELECT m.id, m.organization_id, m.user_id, m.role_id, m.status, m.joined_at, m.created_at, m.updated_at
FROM organization_memberships m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
  AND u.email = $2
  AND m.status = 'active'
`

type GetActiveMembershipByEmailParams struct {
	OrganizationID uuid.UUID
	Email          string
}

// Used to reject inviting someone who is already part of the organization.
func (q *Queries) GetActiveMembershipByEmail(ctx context.Context, arg GetActiveMembershipByEmailParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByEmail, arg.OrganizationID, arg.Email)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at FROM invitations
WHERE id = $1 AND organization_id = $2
`

type GetInvitationByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetInvitationByID(ctx context.Context, arg GetInvitationByIDParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, arg.ID, arg.OrganizationID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByIDForUpdate = `-- name: GetInvitationByIDForUpdate :one
SELECT id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at FROM invitations
WHERE id = $1 AND organization_id = $2
FOR UPDATE
`

type GetInvitationByIDForUpdateParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetInvitationByIDForUpdate(ctx context.Context, arg GetInvitationByIDForUpdateParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByIDForUpdate, arg.ID, arg.OrganizationID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at FROM invitations
WHERE token_hash = $1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByTokenHashForUpdate = `-- name: GetInvitationByTokenHashForUpdate :one
SELECT id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at FROM invitations
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetInvitationByTokenHashForUpdate(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHashForUpdate, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at FROM invitations
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::citext IS NULL OR email = $3::citext)
ORDER BY
    CASE WHEN $4::text = 'created_at' AND NOT $5::bool THEN created_at END ASC,
    CASE WHEN $4::text = 'created_at' AND $5::bool THEN created_at END DESC,
    CASE WHEN $4::text = 'expires_at' AND NOT $5::bool THEN expires_at END ASC,
    CASE WHEN $4::text = 'expires_at' AND $5::bool THEN expires_at END DESC,
    CASE WHEN $4::text = 'email' AND NOT $5::bool THEN email END ASC,
    CASE WHEN $4::text = 'email' AND $5::bool THEN email END DESC,
    id ASC
LIMIT $7::bigint OFFSET $6::bigint
`

type ListInvitationsParams struct {
	OrganizationID uuid.UUID
	Status         *string
	Email          *string
	SortBy         string
	SortDesc       bool
	PageOffset     int64
	PageLimit      int64
}

// Sort keys are fixed CASE branches, so client input never becomes SQL.
func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations,
		arg.OrganizationID,
		arg.Status,
		arg.Email,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.RoleID,
			&i.Status,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationExpired = `-- name: MarkInvitationExpired :one
UPDATE invitations
SET status = 'expired'
WHERE id = $1 AND organization_id = $2 AND status = 'pending'
RETURNING id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at
`

type MarkInvitationExpiredParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) MarkInvitationExpired(ctx context.Context, arg MarkInvitationExpiredParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, markInvitationExpired, arg.ID, arg.OrganizationID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE invitations
SET status = 'revoked',
    revoked_at = $1
WHERE id = $2 AND organization_id = $3
RETURNING id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at
`

type RevokeInvitationParams struct {
	RevokedAt      *time.Time
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.RevokedAt, arg.ID, arg.OrganizationID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rotateInvitationToken = `-- name: RotateInvitationToken :one
UPDATE invitations
SET token_hash = $1,
    expires_at = $2
WHERE id = $3 AND organization_id = $4 AND status = 'pending'
RETURNING id, organization_id, email, role_id, status, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at
`

type RotateInvitationTokenParams struct {
	TokenHash      string
	ExpiresAt      time.Time
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

// Resending reuses the pending invitation and issues a fresh token, so the
// previous link stops working immediately.
func (q *Queries) RotateInvitationToken(ctx context.Context, arg RotateInvitationTokenParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, rotateInvitationToken,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.ID,
		arg.OrganizationID,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
