// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships_extra.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, organization_id, user_id, role_id, status, joined_at, created_at, updated_at FROM organization_memberships
WHERE id = $1 AND organization_id = $2
`

type GetMembershipByIDParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, arg.ID, arg.OrganizationID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembersByOrganization = `-- name: ListMembersByOrganization :many
SELECT
    m.id,
    m.organization_id,
    m.user_id,
    m.role_id,
    m.status,
    m.joined_at,
    m.created_at,
    m.updated_at,
    u.email,
    u.first_name,
    u.last_name,
    r.name AS role_name
FROM organization_memberships m
JOIN users u ON u.id = m.user_id
JOIN roles r ON r.id = m.role_id
WHERE m.organization_id = $1
ORDER BY u.email
`

type ListMembersByOrganizationRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	RoleID         uuid.UUID
	Status         string
	JoinedAt       *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	FirstName      string
	LastName       string
	RoleName       string
}

func (q *Queries) ListMembersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListMembersByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listMembersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByOrganizationRow{}
	for rows.Next() {
		var i ListMembersByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.RoleID,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE organization_memberships
SET role_id = $3
WHERE id = $1 AND organization_id = $2 AND status = 'active'
RETURNING id, organization_id, user_id, role_id, status, joined_at, created_at, updated_at
`

type UpdateMembershipRoleParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	RoleID         uuid.UUID
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.ID, arg.OrganizationID, arg.RoleID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
