// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveOwners = `-- name: CountActiveOwners :one
SELECT count(*)
FROM organization_memberships m
JOIN roles r ON r.id = m.role_id
WHERE m.organization_id = $1
  AND m.status = 'active'
  AND r.name = 'Owner'
`

func (q *Queries) CountActiveOwners(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOwners, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO organization_memberships (organization_id, user_id, role_id, status, joined_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, user_id, role_id, status, joined_at, created_at, updated_at
`

type CreateMembershipParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	RoleID         uuid.UUID
	Status         string
	JoinedAt       *time.Time
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.OrganizationID,
		arg.UserID,
		arg.RoleID,
		arg.Status,
		arg.JoinedAt,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, organization_id, user_id, role_id, status, joined_at, created_at, updated_at FROM organization_memberships
WHERE organization_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.RoleID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT
    m.id, m.organization_id, m.user_id, m.role_id, m.status, m.joined_at, m.created_at, m.updated_at,
    o.name AS organization_name,
    o.slug AS organization_slug,
    o.status AS organization_status,
    r.name AS role_name
FROM organization_memberships m
JOIN organizations o ON o.id = m.organization_id
JOIN roles r ON r.id = m.role_id
WHERE m.user_id = $1 AND m.status = 'active'
ORDER BY o.name
`

type ListMembershipsByUserRow struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	UserID             uuid.UUID
	RoleID             uuid.UUID
	Status             string
	JoinedAt           *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	OrganizationName   string
	OrganizationSlug   string
	OrganizationStatus string
	RoleName           string
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.RoleID,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.OrganizationStatus,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
