// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationMembership struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	RoleID         uuid.UUID
	Status         string
	JoinedAt       *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FamilyID   uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
	UserAgent  *string
	IpAddress  *string
	CreatedAt  time.Time
}

type Role struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    *string
	IsSystem       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	FirstName       string
	LastName        string
	AvatarUrl       *string
	Status          string
	EmailVerifiedAt *time.Time
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
