// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type ActivityLog struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	ResourceType   string
	ResourceID     uuid.UUID
	Metadata       []byte
	CreatedAt      time.Time
}

type ApiKey struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	CreatedBy      uuid.UUID
	Name           string
	KeyPrefix      string
	KeyLastFour    string
	KeyHash        string
	ExpiresAt      time.Time
	RevokedAt      *time.Time
	LastUsedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AuditLog struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
	ActorUserID    *uuid.UUID
	Action         string
	Outcome        string
	TargetType     *string
	TargetID       *string
	IpAddress      *string
	UserAgent      *string
	RequestID      *string
	TraceID        *string
	Metadata       []byte
	CreatedAt      time.Time
}

type Invitation struct {
	ID               uuid.UUID
	OrganizationID   uuid.UUID
	Email            string
	RoleID           uuid.UUID
	Status           string
	TokenHash        string
	InvitedBy        uuid.UUID
	ExpiresAt        time.Time
	AcceptedAt       *time.Time
	AcceptedBy       *uuid.UUID
	RevokedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	NotifiedAt       *time.Time
	DeliveryAttempts int32
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationMembership struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	RoleID         uuid.UUID
	Status         string
	JoinedAt       *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Permission struct {
	ID          uuid.UUID
	Key         string
	Description string
	CreatedAt   time.Time
}

type Project struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	TeamID         *uuid.UUID
	Name           string
	Description    *string
	Status         string
	Priority       string
	StartDate      *time.Time
	DueDate        *time.Time
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FamilyID   uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	ReplacedBy *uuid.UUID
	UserAgent  *string
	IpAddress  *string
	CreatedAt  time.Time
}

type Role struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    *string
	IsSystem       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type Task struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	ProjectID      uuid.UUID
	Title          string
	Description    *string
	Status         string
	Priority       string
	AssigneeID     *uuid.UUID
	DueDate        *time.Time
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Team struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    *string
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TeamMember struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	TeamID         uuid.UUID
	UserID         uuid.UUID
	CreatedAt      time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	FirstName       string
	LastName        string
	AvatarUrl       *string
	Status          string
	EmailVerifiedAt *time.Time
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
