// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR priority = $3::text)
  AND ($4::uuid IS NULL OR team_id = $4::uuid)
`

type CountProjectsParams struct {
	OrganizationID uuid.UUID
	Status         *string
	Priority       *string
	TeamID         *uuid.UUID
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects,
		arg.OrganizationID,
		arg.Status,
		arg.Priority,
		arg.TeamID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    organization_id, team_id, name, description, status, priority,
    start_date, due_date, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, team_id, name, description, status, priority, start_date, due_date, created_by, created_at, updated_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID
	TeamID         *uuid.UUID
	Name           string
	Description    *string
	Status         string
	Priority       string
	StartDate      *time.Time
	DueDate        *time.Time
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.StartDate,
		arg.DueDate,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1 AND organization_id = $2
`

type DeleteProjectParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OrganizationID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, organization_id, team_id, name, description, status, priority, start_date, due_date, created_by, created_at, updated_at FROM projects
WHERE id = $1 AND organization_id = $2
`

type GetProjectParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForUpdate = `-- name: GetProjectForUpdate :one
SELECT id, organization_id, team_id, name, description, status, priority, start_date, due_date, created_by, created_at, updated_at FROM projects
WHERE id = $1 AND organization_id = $2
FOR UPDATE
`

type GetProjectForUpdateParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetProjectForUpdate(ctx context.Context, arg GetProjectForUpdateParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUpdate, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, organization_id, team_id, name, description, status, priority, start_date, due_date, created_by, created_at, updated_at FROM projects
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR priority = $3::text)
  AND ($4::uuid IS NULL OR team_id = $4::uuid)
ORDER BY
    CASE WHEN $5::text = 'name' AND NOT $6::bool THEN name END ASC,
    CASE WHEN $5::text = 'name' AND $6::bool THEN name END DESC,
    CASE WHEN $5::text = 'created_at' AND NOT $6::bool THEN created_at END ASC,
    CASE WHEN $5::text = 'created_at' AND $6::bool THEN created_at END DESC,
    CASE WHEN $5::text = 'updated_at' AND NOT $6::bool THEN updated_at END ASC,
    CASE WHEN $5::text = 'updated_at' AND $6::bool THEN updated_at END DESC,
    CASE WHEN $5::text = 'due_date' AND NOT $6::bool THEN due_date END ASC NULLS LAST,
    CASE WHEN $5::text = 'due_date' AND $6::bool THEN due_date END DESC NULLS LAST,
    CASE WHEN $5::text = 'priority' AND NOT $6::bool
        THEN array_position(ARRAY['low', 'medium', 'high', 'urgent']::text[], priority) END ASC,
    CASE WHEN $5::text = 'priority' AND $6::bool
        THEN array_position(ARRAY['low', 'medium', 'high', 'urgent']::text[], priority) END DESC,
    id ASC
LIMIT $8::bigint OFFSET $7::bigint
`

type ListProjectsParams struct {
	OrganizationID uuid.UUID
	Status         *string
	Priority       *string
	TeamID         *uuid.UUID
	SortBy         string
	SortDesc       bool
	PageOffset     int64
	PageLimit      int64
}

// Sort keys are fixed CASE branches, so client input never becomes SQL.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.OrganizationID,
		arg.Status,
		arg.Priority,
		arg.TeamID,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.StartDate,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET team_id = $3,
    name = $4,
    description = $5,
    status = $6,
    priority = $7,
    start_date = $8,
    due_date = $9
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, team_id, name, description, status, priority, start_date, due_date, created_by, created_at, updated_at
`

type UpdateProjectParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	TeamID         *uuid.UUID
	Name           string
	Description    *string
	Status         string
	Priority       string
	StartDate      *time.Time
	DueDate        *time.Time
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.OrganizationID,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.StartDate,
		arg.DueDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
