// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (Invitation, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	CountAPIKeys(ctx context.Context, arg CountAPIKeysParams) (int64, error)
	CountActiveOwners(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountActivityByResource(ctx context.Context, arg CountActivityByResourceParams) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountInvitations(ctx context.Context, arg CountInvitationsParams) (int64, error)
	CountMembershipsByRole(ctx context.Context, arg CountMembershipsByRoleParams) (int64, error)
	CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error)
	CountTasks(ctx context.Context, arg CountTasksParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	DeleteTeam(ctx context.Context, arg DeleteTeamParams) error
	// Authentication resolves a key by hash before a tenant is known, so this lookup
	// runs without an RLS tenant context, exactly like the login lookup by email.
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error)
	GetAPIKeyByIDForUpdate(ctx context.Context, arg GetAPIKeyByIDForUpdateParams) (ApiKey, error)
	// Used to reject inviting someone who is already part of the organization.
	GetActiveMembershipByEmail(ctx context.Context, arg GetActiveMembershipByEmailParams) (OrganizationMembership, error)
	GetInvitationByID(ctx context.Context, arg GetInvitationByIDParams) (Invitation, error)
	// Resolves an invitation's organization from an id that came from the job queue
	// rather than from a request, so the worker can open a tenant transaction for
	// it. It is never used to serve client input.
	GetInvitationByIDForJob(ctx context.Context, id uuid.UUID) (GetInvitationByIDForJobRow, error)
	GetInvitationByIDForUpdate(ctx context.Context, arg GetInvitationByIDForUpdateParams) (Invitation, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error)
	GetInvitationByTokenHashForUpdate(ctx context.Context, tokenHash string) (Invitation, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error)
	GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (OrganizationMembership, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPermissionByKey(ctx context.Context, key string) (Permission, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetProjectForUpdate(ctx context.Context, arg GetProjectForUpdateParams) (Project, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error)
	GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetTaskForUpdate(ctx context.Context, arg GetTaskForUpdateParams) (Task, error)
	GetTeam(ctx context.Context, arg GetTeamParams) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	HasRolePermission(ctx context.Context, arg HasRolePermissionParams) (bool, error)
	// Sort keys are fixed CASE branches, so client input never becomes SQL.
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error)
	// Background maintenance jobs enumerate tenants and then run tenant-scoped work
	// inside each organization's own transaction.
	ListActiveOrganizationIDs(ctx context.Context, rowLimit int64) ([]uuid.UUID, error)
	ListActivityByResource(ctx context.Context, arg ListActivityByResourceParams) ([]ActivityLog, error)
	// Reads are always tenant-scoped; rows without an organization are excluded by the
	// RLS select policy and can never be reached through this query.
	// ip_address is selected as text: pgx cannot scan the inet type into a Go string,
	// and the text form is what the API exposes anyway. An absent address becomes an
	// empty string, which the client-facing entry omits.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	// Expired keys that have been dead long enough to be worth revoking. The grace
	// period keeps recently expired keys visible for an operator to review.
	ListExpiredAPIKeys(ctx context.Context, arg ListExpiredAPIKeysParams) ([]ApiKey, error)
	// Sort keys are fixed CASE branches, so client input never becomes SQL.
	ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error)
	ListMembersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListMembersByOrganizationRow, error)
	ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error)
	ListPermissionKeysByRole(ctx context.Context, roleID uuid.UUID) ([]string, error)
	// Sort keys are fixed CASE branches, so client input never becomes SQL.
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListRolesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Role, error)
	// Sort keys are fixed CASE branches, so client input never becomes SQL.
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context, organizationID uuid.UUID) ([]Team, error)
	ListUndeliveredInvitations(ctx context.Context, arg ListUndeliveredInvitationsParams) ([]Invitation, error)
	MarkInvitationExpired(ctx context.Context, arg MarkInvitationExpiredParams) (Invitation, error)
	// Records that the invitation email reached a transport.
	MarkInvitationNotified(ctx context.Context, arg MarkInvitationNotifiedParams) error
	OrganizationSlugExists(ctx context.Context, slug string) (bool, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	RevokeAPIKeyByID(ctx context.Context, arg RevokeAPIKeyByIDParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (Invitation, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	// The redelivery sweep issues a fresh token for an invitation that was never
	// queued. Rotating invalidates the previous link, which is safe because it was
	// never delivered, and increments the attempt counter so a permanently failing
	// transport is not retried forever.
	RotateInvitationForDelivery(ctx context.Context, arg RotateInvitationForDeliveryParams) (Invitation, error)
	// Resending reuses the pending invitation and issues a fresh token, so the
	// previous link stops working immediately.
	RotateInvitationToken(ctx context.Context, arg RotateInvitationTokenParams) (Invitation, error)
	SetRolePermissions(ctx context.Context, roleID uuid.UUID) error
	// Throttled to one write per minute per key so recording usage does not double
	// the write load of every authenticated request.
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (OrganizationMembership, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
