// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	CountActiveOwners(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountMembershipsByRole(ctx context.Context, arg CountMembershipsByRoleParams) (int64, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error)
	GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (OrganizationMembership, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPermissionByKey(ctx context.Context, key string) (Permission, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error)
	GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	HasRolePermission(ctx context.Context, arg HasRolePermissionParams) (bool, error)
	ListMembersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListMembersByOrganizationRow, error)
	ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error)
	ListPermissionKeysByRole(ctx context.Context, roleID uuid.UUID) ([]string, error)
	ListRolesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Role, error)
	OrganizationSlugExists(ctx context.Context, slug string) (bool, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	SetRolePermissions(ctx context.Context, roleID uuid.UUID) error
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (OrganizationMembership, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
