// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTasks = `-- name: CountTasks :one
SELECT count(*) FROM tasks
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR priority = $4::text)
  AND (
      ($5::uuid IS NOT NULL AND assignee_id = $5::uuid)
      OR ($5::uuid IS NULL AND $6::bool AND assignee_id IS NULL)
      OR ($5::uuid IS NULL AND NOT $6::bool)
  )
`

type CountTasksParams struct {
	OrganizationID uuid.UUID
	ProjectID      *uuid.UUID
	Status         *string
	Priority       *string
	AssigneeID     *uuid.UUID
	Unassigned     bool
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.Unassigned,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    organization_id, project_id, title, description, status, priority,
    assignee_id, due_date, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, project_id, title, description, status, priority, assignee_id, due_date, created_by, created_at, updated_at
`

type CreateTaskParams struct {
	OrganizationID uuid.UUID
	ProjectID      uuid.UUID
	Title          string
	Description    *string
	Status         string
	Priority       string
	AssigneeID     *uuid.UUID
	DueDate        *time.Time
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND organization_id = $2
`

type DeleteTaskParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OrganizationID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, organization_id, project_id, title, description, status, priority, assignee_id, due_date, created_by, created_at, updated_at FROM tasks
WHERE id = $1 AND organization_id = $2
`

type GetTaskParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.OrganizationID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, organization_id, project_id, title, description, status, priority, assignee_id, due_date, created_by, created_at, updated_at FROM tasks
WHERE id = $1 AND organization_id = $2
FOR UPDATE
`

type GetTaskForUpdateParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetTaskForUpdate(ctx context.Context, arg GetTaskForUpdateParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForUpdate, arg.ID, arg.OrganizationID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, organization_id, project_id, title, description, status, priority, assignee_id, due_date, created_by, created_at, updated_at FROM tasks
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR priority = $4::text)
  AND (
      ($5::uuid IS NOT NULL AND assignee_id = $5::uuid)
      OR ($5::uuid IS NULL AND $6::bool AND assignee_id IS NULL)
      OR ($5::uuid IS NULL AND NOT $6::bool)
  )
ORDER BY
    CASE WHEN $7::text = 'title' AND NOT $8::bool THEN title END ASC,
    CASE WHEN $7::text = 'title' AND $8::bool THEN title END DESC,
    CASE WHEN $7::text = 'created_at' AND NOT $8::bool THEN created_at END ASC,
    CASE WHEN $7::text = 'created_at' AND $8::bool THEN created_at END DESC,
    CASE WHEN $7::text = 'updated_at' AND NOT $8::bool THEN updated_at END ASC,
    CASE WHEN $7::text = 'updated_at' AND $8::bool THEN updated_at END DESC,
    CASE WHEN $7::text = 'due_date' AND NOT $8::bool
        THEN due_date END ASC NULLS LAST,
    CASE WHEN $7::text = 'due_date' AND $8::bool
        THEN due_date END DESC NULLS LAST,
    CASE WHEN $7::text = 'priority' AND NOT $8::bool
        THEN array_position(ARRAY['low', 'medium', 'high', 'urgent']::text[], priority) END ASC,
    CASE WHEN $7::text = 'priority' AND $8::bool
        THEN array_position(ARRAY['low', 'medium', 'high', 'urgent']::text[], priority) END DESC,
    CASE WHEN $7::text = 'status' AND NOT $8::bool
        THEN array_position(
            ARRAY['todo', 'in_progress', 'blocked', 'in_review', 'done', 'cancelled']::text[], status) END ASC,
    CASE WHEN $7::text = 'status' AND $8::bool
        THEN array_position(
            ARRAY['todo', 'in_progress', 'blocked', 'in_review', 'done', 'cancelled']::text[], status) END DESC,
    id ASC
LIMIT $10::bigint OFFSET $9::bigint
`

type ListTasksParams struct {
	OrganizationID uuid.UUID
	ProjectID      *uuid.UUID
	Status         *string
	Priority       *string
	AssigneeID     *uuid.UUID
	Unassigned     bool
	SortBy         string
	SortDesc       bool
	PageOffset     int64
	PageLimit      int64
}

// Sort keys are fixed CASE branches, so client input never becomes SQL.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.Unassigned,
		arg.SortBy,
		arg.SortDesc,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $3,
    description = $4,
    status = $5,
    priority = $6,
    assignee_id = $7,
    due_date = $8
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, project_id, title, description, status, priority, assignee_id, due_date, created_by, created_at, updated_at
`

type UpdateTaskParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Title          string
	Description    *string
	Status         string
	Priority       string
	AssigneeID     *uuid.UUID
	DueDate        *time.Time
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.OrganizationID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
