// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (organization_id, team_id, user_id)
VALUES ($1, $2, $3)
RETURNING id, organization_id, team_id, user_id, created_at
`

type AddTeamMemberParams struct {
	OrganizationID uuid.UUID
	TeamID         uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.OrganizationID, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (organization_id, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, description, created_by, created_at, updated_at
`

type CreateTeamParams struct {
	OrganizationID uuid.UUID
	Name           string
	Description    *string
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1 AND organization_id = $2
`

type DeleteTeamParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) DeleteTeam(ctx context.Context, arg DeleteTeamParams) error {
	_, err := q.db.Exec(ctx, deleteTeam, arg.ID, arg.OrganizationID)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, organization_id, name, description, created_by, created_at, updated_at FROM teams
WHERE id = $1 AND organization_id = $2
`

type GetTeamParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.ID, arg.OrganizationID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id, tm.organization_id, tm.team_id, tm.user_id, tm.created_at,
       u.email, u.first_name, u.last_name
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1 AND tm.organization_id = $2
ORDER BY u.email
`

type ListTeamMembersParams struct {
	TeamID         uuid.UUID
	OrganizationID uuid.UUID
}

type ListTeamMembersRow struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	TeamID         uuid.UUID
	UserID         uuid.UUID
	CreatedAt      time.Time
	Email          string
	FirstName      string
	LastName       string
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, arg.TeamID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.UserID,
			&i.CreatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, organization_id, name, description, created_by, created_at, updated_at FROM teams
WHERE organization_id = $1
ORDER BY name
`

func (q *Queries) ListTeams(ctx context.Context, organizationID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE id = $1 AND team_id = $2 AND organization_id = $3
`

type RemoveTeamMemberParams struct {
	ID             uuid.UUID
	TeamID         uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.ID, arg.TeamID, arg.OrganizationID)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $3, description = $4
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, created_by, created_at, updated_at
`

type UpdateTeamParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    *string
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
